name = "math-hub"
main = "src/index.js"
compatibility_date = "2024-11-01"

[assets]
directory = "./"
binding = "ASSETS"

[[kv_namespaces]]
binding = "PUSH_SUBS"
id = "2bcca653989f47ca955175cb82b3025a"
